version: 0.2

env:
  parameter-store:
    GITHUB_TOKEN: "/github/token"

phases:
  pre_build:
    commands:
      - echo $GITHUB_TOKEN
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - REPOSITORY_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/portfolio
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  
  build:
    commands:
      - echo Building Docker Image...
      - docker build -t $REPOSITORY_URL:$IMAGE_TAG .
      - docker tag $REPOSITORY_URL:$IMAGE_TAG $REPOSITORY_URL:latest

  post_build:
    commands:
      - echo Pushing to ECR...
      - docker push $REPOSITORY_URL:$IMAGE_TAG
      - docker push $REPOSITORY_URL:latest
      - echo Writing imagefinitions.json...
      - printf '[{"name":"app-container","imageUri":"%s"}]' $REPOSITORY_URL:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json