AWSTemplateFormatVersion: "2010-09-09"
Description: Master Nested Stack to deploy portfolio infrastructure components

Parameters:
  TemplateBucket:
    Type: String
    Description: S3 Bucket containing the nested templates
  TemplatePrefix:
    Type: String
    Description: Optional prefix (Folder) in the bucket (e.g., "infra/")

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/${TemplatePrefix}VPC.yml

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/${TemplatePrefix}LoadBalancer.yml
  
  LaunchTemplateStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/${TemplatePrefix}LaunchTemplate.yml

  ServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/${TemplatePrefix}Service.yml

  PipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/${TemplatePrefix}DeploymentPipeline.yml

  AutoScalingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/${TemplatePrefix}AutoScalingGroup.yml

